# Generated by Django 5.1 on 2024-08-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_studentmodel_delete_login_delete_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='QureyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=49)),
                ('email', models.EmailField(max_length=254)),
                ('qurey', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
